image: maven:3-jdk-8
cache:
  - /root/.m2/repository
script:
  - mkdir ~/.taskroo
  - cp src/main/resources/local.properties ~/.taskroo/.
  - curl -s https://get.docker.io/ubuntu/ | sudo sh
  - mvn -Pdeploy -DargLine="-DMONGO_PORT_27017_TCP_PORT=$MONGO_PORT_27017_TCP_PORT -DMONGO_PORT_27017_TCP_ADDR=$MONGO_PORT_27017_TCP_ADDR"
  - docker push taskroo/taskroo-api
services:
  - maniekq/mongo:2.6
notify:  
  email:
    recipients:
      - {{emailMariusz}}
