image: maven:3-jdk-8
script:
  - curl -sSL http://archive.apache.org/dist/maven/maven-3/3.2.5/binaries/apache-maven-3.2.5-bin.tar.gz | tar xzf - -C /usr/share && mv /usr/share/apache-maven-3.2.5 /usr/share/maven && ln -s /usr/share/maven/bin/mvn /usr/bin/mvn
  - mvn install -DskipTests
services:
  - library/mongo:3.0

