image: maven:3-jdk-8
cache:
  - ~/.m2/repository
script:
  - mvn install -DargLine="-DMONGO_PORT_27017_TCP_PORT=$MONGO_PORT_27017_TCP_PORT -DMONGO_PORT_27017_TCP_ADDR=$MONGO_PORT_27017_TCP_ADDR"
services:
  - maniekq/mongo:2.6
